version: '3.6'

services:
  
  stellar:
    # in order to run this container you must do a 'docker-compose run stellar' to run the image in interactive mode
    # this will create the database. You must specify a pwd for the db
    # when setting up this image, you have to empty the stellar-config directory, in order to force the db creation
    # after db creation, stop the image ctrl+c and restart it 'docker-compose -f docker-compose-stellar.yml up/start stellar'
    # one can then connect to the db via port 5434 with user stellar and password provided
    stdin_open: true
    tty: true
    #build:
    #  context: stellar-core
    #  dockerfile: Dockerfile

    #restart: always
    restart: "no"
    image: stellar/quickstart:testing
    volumes:
      - stellar-data:/opt/stellar/postgresql/data        
      - ./stellar-config:/opt/stellar           
      
    command: --testnet    
    ports:
      - "5434:5432"
      - "8002:8000"
      - "11625:11625"
      - "11626:11626"  
      
# please create the data volumes external with this command
# docker volume create --name stellar-data -d local
volumes:
  stellar-data:
    external: true
